# Copyright (c) 2020 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

title: Digital Assistant External Services
description: Digital Assistant External Services
schemaVersion: 1.1.0
version: "20190304"
locale: "en"

variableGroups:
  - title: "Hidden"
    variables:
      - compartment_ocid
      - tenancy_ocid
      - user_ocid
      - region
      - fingerprint
      - private_key_path
      - oke-worker-node-shape
      - network_cidrs
      - network_names
    visible: false

  - title: "Configuration"
    variables:
      - oke-cluster-name
      - oke-worker-node-shape
      - apigateway_name

variables:
  oke-cluster-name:
    type: string
    title: "OKE Cluster Name"
    default: "Digital Assistant OKE Cluster"
    required: true
    visibe: true

  apigateway_name:
    type: string
    title: "API Gateway Name"
    required: true
    default: "Digital Assistant API Gateway"

  oke-worker-node-shape:
    type: oci:core:instanceshape:name
    default: "VM.Standard.E3.Flex"
    title: "OKE Worker Nodes Compute Shape"
    visible: false
    required: true
    dependsOn:
      compartmentId: ${compartment_ocid}

#  region:
#    type: oci:identity:region:name
#    required: true
#    visible: true
#
#  compartment_ocid:
#    type: oci:identity:compartment:id
#    required: true
#    title: "Compartment"
#    visible: true
#
#  tenancy_ocid:
#    type: string
#    required: true
#    visible: false
